Repository google/certificate-transparency, pull requests merged in 2018-09, with the labels that each got.

#1454 openssl_generator.py: Replace ':' in log identifier with '_'
  python/utilities/log_list/openssl_generator.py
Labels: bug, cla: yes

#1452 Replace M2Crypto usage in print_log_list.py with cryptography.io
  python/utilities/log_list/print_log_list.py
Labels: cla: yes, portability

#1453 Use absl.app in print_log_list.py and improve flag checks
  python/utilities/log_list/print_log_list.py
Labels: cla: yes, enhancement

#1455 Reserve space in path vector prior to populating it
  cpp/log/log_verifier.cc
Labels: cla: yes

#1456 Apply a few cleanups to the code.
  cpp/log/cert_checker_test.cc
  cpp/log/cert_test.cc
  cpp/log/logged_entry.cc
Labels: cla: yes
